window.w = [
// --- CLASSIC CHARACTERS & VINTAGE ---
{ "word": "Mortimer Mouse", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Clara Cluck", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Ludwig Von Drake", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "April", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "May", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "June", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Gladstone Gander", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Magica De Spell", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Flintheart Glomgold", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Beagle Boys", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Gyro Gearloose", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Fiddler Pig", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Fifer Pig", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Practical Pig", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Big Bad Wolf", "topic": "Disney Villains", "difficulty": "Easy" },
{ "word": "Max Hare", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Toby Tortoise", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Willie the Giant", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "J. Thaddeus Toad", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Ichabod Crane", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Headless Horseman", "topic": "Disney Villains", "difficulty": "Medium" },

// --- WINNIE THE POOH & FRIENDS ---
{ "word": "Rabbit", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Owl", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Kanga", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Gopher", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Lumpy", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Heffalump", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Woozle", "topic": "Disney Characters", "difficulty": "Medium" },

// --- PRINCESS COMPANIONS & ROYALTY ---
{ "word": "King Triton", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Grimsby", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Chef Louis", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Maurice", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Wardrobe", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Featherduster", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Footstool", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Sultan", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Rajah", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "King Stefan", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "King Hubert", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Queen Leah", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Flora", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Fauna", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Merryweather", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Samson", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Chief Powhatan", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Grandmother Willow", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Nakoma", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Percy", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Emperor of China", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Cri-Kee", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Khan", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Little Brother", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Chien-Po", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Yao", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Ling", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Charlotte La Bouff", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Big Daddy", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Mama Odie", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Eudora", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "King Agnarr", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Queen Iduna", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Grand Pabbie", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Bulda", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Oaken", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Marshmallow", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Bruni", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Chief Tui", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Sina", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Gramma Tala", "topic": "Disney Characters", "difficulty": "Medium" },

// --- THE MADRIGALS (ENCANTO) ---
{ "word": "Abuela Alma", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Julieta", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Agustin", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Pepa", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Felix", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Dolores", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Camilo", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Antonio", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Isabela", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Luisa", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Mariano", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Pico", "topic": "Disney Characters", "difficulty": "Hard" },

// --- HEROIC ANIMALS & SIDEKICKS ---
{ "word": "Pongo", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Perdita", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Lucky", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Patch", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Rolly", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Lady", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Tramp", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Jock", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Trusty", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Duchess", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Thomas O'Malley", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Marie", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Berlioz", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Toulouse", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Roquefort", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Bernard", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Bianca", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Orville", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Wilbur", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Tod", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Copper", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Big Mama", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Basil of Baker Street", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Dr. Dawson", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Olivia Flaversham", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Oliver", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Dodger", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Tito", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Einstein", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Francis", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Georgette", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Rita", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Cody", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Marahute", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Joanna", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Max", "topic": "Disney Characters", "difficulty": "Medium" }, // Eric's Dog
{ "word": "Nana", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Djali", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Achilles", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Sabor", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Kala", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Kerchak", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Professor Porter", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Rutt", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Tuke", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Koda", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Kenai", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Sitka", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Denahi", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Maggie", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Mrs. Caloway", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Grace", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Buck Cluck", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Abby Mallard", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Runt of the Litter", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Fish Out of Water", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Rhino", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Mittens", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Penny", "topic": "Disney Characters", "difficulty": "Hard" },

// --- VILLAIN HENCHMEN & SIDEKICKS ---
{ "word": "LeFou", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Shenzi", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Banzai", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Ed", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Flotsam", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Jetsam", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Pain", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Panic", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Sir Hiss", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Sheriff of Nottingham", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Jasper", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Horace", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Mr. Snoops", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Fidget", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Tick-Tock the Crocodile", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Diablo", "topic": "Disney Villains", "difficulty": "Hard" }, // Maleficent's Raven
{ "word": "Hayabusa", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Lawrence", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Stabbington Brothers", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Duke of Weselton", "topic": "Disney Villains", "difficulty": "Hard" },

// --- PIXAR DEEP DIVE ---
{ "word": "Andy Davis", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Molly Davis", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Buster", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Bullseye", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Stinky Pete", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Al McWhiggin", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Wheezy", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Barbie", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Ken", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Big Baby", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Buttercup", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Mr. Pricklepants", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Trixie", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Dolly", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Bonnie", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Duke Caboom", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Ducky", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Bunny", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Gabby Gabby", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Princess Atta", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Heimlich", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Francis", "topic": "Pixar", "difficulty": "Hard" }, // Bug
{ "word": "Tuck", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Roll", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "P.T. Flea", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Roz", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Celia Mae", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "The Yeti", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "George Sanderson", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Mr. Waternoose", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Gill", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Bloat", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Peach", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Gurgle", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Bubbles", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Deb", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Jacques", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Nigel", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Bruce", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Anchor", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Chum", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Mr. Ray", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Darla", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Mirage", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "The Underminer", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Kari McKeen", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Rick Dicker", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Voyd", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Screenslaver", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Luigi", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Guido", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Ramone", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Flo", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Sheriff", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Fillmore", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Sarge", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Lizzie", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Red", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Mack", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Chick Hicks", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "The King", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Finn McMissile", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Holley Shiftwell", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Francesco Bernoulli", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Jackson Storm", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Cruz Ramirez", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Skinner", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Anton Ego", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Auguste Gusteau", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Colette", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Django", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Alpha", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Beta", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Gamma", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Ellie", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Charles Muntz", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Queen Elinor", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "King Fergus", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "The Witch", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Harris", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Hubert", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Hamish", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Mor'du", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Oozma Kappa", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Art", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Squishy", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Don Carlton", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Terri and Terry", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Dean Hardscrabble", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Jangles", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Butch", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Ramsey", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Nash", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Hank", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Destiny", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Bailey", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Jenny", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Charlie", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Imelda", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Pepita", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Abuelita", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Chicharron", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Laurel Lightfoot", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "The Manticore", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Blazey", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Jerry", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Terry", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Mr. Mittens", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Moonwind", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Giulia Marcovaldo", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Massimo", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Ercole Visconti", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Machiavelli", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Ming Lee", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Miriam", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Priya", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Abby", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Jin Lee", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "4*Town", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Sox", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Izzy Hawthorne", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Mo Morrison", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Darby Steel", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Gale", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Clod", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Bernie Lumen", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Cinder Lumen", "topic": "Pixar", "difficulty": "Hard" },

// --- DISNEY CHANNEL & TV FAVORITES ---
{ "word": "Phineas", "topic": "Disney Channel", "difficulty": "Easy" },
{ "word": "Ferb", "topic": "Disney Channel", "difficulty": "Easy" },
{ "word": "Candace", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Perry the Platypus", "topic": "Disney Channel", "difficulty": "Easy" },
{ "word": "Dr. Doofenshmirtz", "topic": "Disney Channel", "difficulty": "Easy" },
{ "word": "Isabella", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Baljeet", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Buford", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Kim Possible", "topic": "Disney Channel", "difficulty": "Easy" },
{ "word": "Ron Stoppable", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Rufus", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Shego", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Dr. Drakken", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Hannah Montana", "topic": "Disney Channel", "difficulty": "Easy" },
{ "word": "Miley Stewart", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Lizzie McGuire", "topic": "Disney Channel", "difficulty": "Easy" },
{ "word": "Raven Baxter", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Zack Martin", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Cody Martin", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "London Tipton", "topic": "Disney Channel", "difficulty": "Hard" },
{ "word": "Mr. Moseby", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Troy Bolton", "topic": "Disney Channel", "difficulty": "Easy" },
{ "word": "Gabriella Montez", "topic": "Disney Channel", "difficulty": "Easy" },
{ "word": "Sharpay Evans", "topic": "Disney Channel", "difficulty": "Easy" },
{ "word": "Ryan Evans", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Chad Danforth", "topic": "Disney Channel", "difficulty": "Hard" },
{ "word": "Mal", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Evie", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Carlos", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Jay", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Bill Cipher", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Dipper Pines", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Mabel Pines", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Grunkle Stan", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Soos", "topic": "Disney Channel", "difficulty": "Hard" },
{ "word": "Wendy Corduroy", "topic": "Disney Channel", "difficulty": "Hard" },
{ "word": "Star Butterfly", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Marco Diaz", "topic": "Disney Channel", "difficulty": "Medium" },
{ "word": "Anne Boonchuy", "topic": "Disney Channel", "difficulty": "Hard" },
{ "word": "Luz Noceda", "topic": "Disney Channel", "difficulty": "Hard" },
{ "word": "Eda the Owl Lady", "topic": "Disney Channel", "difficulty": "Hard" },
{ "word": "King", "topic": "Disney Channel", "difficulty": "Hard" },

// --- THE MUPPETS (Disney Owned) ---
{ "word": "Kermit the Frog", "topic": "Muppets", "difficulty": "Easy" },
{ "word": "Miss Piggy", "topic": "Muppets", "difficulty": "Easy" },
{ "word": "Fozzie Bear", "topic": "Muppets", "difficulty": "Medium" },
{ "word": "Gonzo", "topic": "Muppets", "difficulty": "Medium" },
{ "word": "Animal", "topic": "Muppets", "difficulty": "Medium" },
{ "word": "Beaker", "topic": "Muppets", "difficulty": "Medium" },
{ "word": "Dr. Bunsen Honeydew", "topic": "Muppets", "difficulty": "Hard" },
{ "word": "Swedish Chef", "topic": "Muppets", "difficulty": "Medium" },
{ "word": "Statler", "topic": "Muppets", "difficulty": "Hard" },
{ "word": "Waldorf", "topic": "Muppets", "difficulty": "Hard" },
{ "word": "Rizzo the Rat", "topic": "Muppets", "difficulty": "Hard" },
{ "word": "Rowlf", "topic": "Muppets", "difficulty": "Hard" },
{ "word": "Scooter", "topic": "Muppets", "difficulty": "Hard" },
{ "word": "Pepe the King Prawn", "topic": "Muppets", "difficulty": "Hard" },
{ "word": "Walter", "topic": "Muppets", "difficulty": "Hard" },
{ "word": "Constantine", "topic": "Muppets", "difficulty": "Hard" },

// --- LIVE ACTION & OTHER MOVIES ---
{ "word": "Jack Skellington", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Sally", "topic": "Disney Characters", "difficulty": "Medium" }, // Nightmare Before Christmas
{ "word": "Zero", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Mayor of Halloween Town", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Lock", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Shock", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Barrel", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Jack Sparrow", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Will Turner", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Elizabeth Swann", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Hector Barbossa", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Davy Jones", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Tia Dalma", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Gibbs", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Mary Poppins", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Bert", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Jane Banks", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Michael Banks", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Winifred Sanderson", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Sarah Sanderson", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Mary Sanderson", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Binx", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Billy Butcherson", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Herbie", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Tron", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Sark", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Quorra", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Kevin Flynn", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Sam Flynn", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "George of the Jungle", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Mia Thermopolis", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Queen Clarisse Renaldi", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Fat Louie", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Hallie Parker", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Annie James", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Meredith Blake", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Chessy", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Martin", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Scott Calvin", "topic": "Disney Characters", "difficulty": "Medium" }, // The Santa Clause
{ "word": "Bernard the Elf", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Wayne Szalinski", "topic": "Disney Characters", "difficulty": "Hard" }, // Honey I Shrunk the Kids
{ "word": "Professor Brainard", "topic": "Disney Characters", "difficulty": "Hard" }, // Flubber
{ "word": "Weebo", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Rocketeer", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Mighty Ducks", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Gordon Bombay", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Charlie Conway", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Goldberg", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Cool Runnings", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Sanka Coffie", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Frank Wolff", "topic": "Disney Characters", "difficulty": "Hard" }, // Jungle Cruise
{ "word": "Lily Houghton", "topic": "Disney Characters", "difficulty": "Hard" },

// --- UNDERRATED ANIMATED MOVIES ---
{ "word": "Atlantis: The Lost Empire", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Milo Thatch", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Kida", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Helga Sinclair", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Commander Rourke", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Vinny Santorini", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Mole", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Audrey Ramirez", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Dr. Sweet", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Treasure Planet", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Jim Hawkins", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Long John Silver", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Morph", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "B.E.N.", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Captain Amelia", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Dr. Doppler", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Scroop", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "The Black Cauldron", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "Taran", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Princess Eilonwy", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Gurgi", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "The Horned King", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "The Sword in the Stone", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Merlin", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Archimedes", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Pete's Dragon", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Elliott", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Bedknobs and Broomsticks", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "Eglantine Price", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Swiss Family Robinson", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "Old Yeller", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "James and the Giant Peach", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "Frankenweenie", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Sparky", "topic": "Disney Characters", "difficulty": "Medium" },

// --- DISNEY PARKS & EXPERIENCES ---
{ "word": "Spaceship Earth", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Tree of Life", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Expedition Everest", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Kilimanjaro Safaris", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Dinosaur", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Pandora", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Flight of Passage", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Na'vi River Journey", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Soarin'", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Test Track", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Mission: SPACE", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "The Living Seas", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "The Land", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Figment", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Dreamfinder", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "World Showcase", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Mexico Pavilion", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Norway Pavilion", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "France Pavilion", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Rock 'n' Roller Coaster", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Slinky Dog Dash", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Toy Story Mania", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Star Tours", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Galaxy's Edge", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Millennium Falcon: Smugglers Run", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Rise of the Resistance", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Oga's Cantina", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Fantasmic!", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Seven Dwarfs Mine Train", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Peter Pan's Flight", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "The Many Adventures of Winnie the Pooh", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Dumbo the Flying Elephant", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Mad Tea Party", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Carousel of Progress", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "PeopleMover", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Astro Orbiter", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Monorail", "topic": "Disney Parks", "difficulty": "Easy" },
{ "word": "Disney Skyliner", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Typhoon Lagoon", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Blizzard Beach", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Disney Springs", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Bibbidi Bobbidi Boutique", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Club 33", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Matterhorn Bobsleds", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Mr. Toad's Wild Ride", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Finding Nemo Submarine Voyage", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Incredicoaster", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Pixar Pal-A-Round", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Radiator Springs Racers", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Guardians of the Galaxy: Cosmic Rewind", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "TRON Lightcycle / Run", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Turkey Leg", "topic": "Disney Food", "difficulty": "Medium" },
{ "word": "Mickey Waffle", "topic": "Disney Food", "difficulty": "Easy" },
{ "word": "Popcorn Bucket", "topic": "Disney Food", "difficulty": "Medium" },
{ "word": "Corn Dog Nuggets", "topic": "Disney Food", "difficulty": "Hard" },
{ "word": "Blue Milk", "topic": "Disney Food", "difficulty": "Hard" },
{ "word": "Green Milk", "topic": "Disney Food", "difficulty": "Hard" },
{ "word": "Kitchen Sink Sundae", "topic": "Disney Food", "difficulty": "Hard" },
{ "word": "MagicBand", "topic": "Disney Items", "difficulty": "Medium" },
{ "word": "FastPass", "topic": "Disney Items", "difficulty": "Medium" },
{ "word": "Lightning Lane", "topic": "Disney Items", "difficulty": "Medium" },
{ "word": "Hidden Mickey", "topic": "Disney Items", "difficulty": "Medium" },
{ "word": "Pin Trading", "topic": "Disney Items", "difficulty": "Medium" },

// --- ADDITIONAL SONGS & MUSIC ---
{ "word": "Feed the Birds", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Chim Chim Cher-ee", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Step in Time", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Bella Notte", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Someday My Prince Will Come", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Once Upon a Dream", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "So This Is Love", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Kiss the Girl", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "Friend Like Me", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "Prince Ali", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "One Jump Ahead", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Arabian Nights", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Can You Feel the Love Tonight", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "Just Around the Riverbend", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Savages", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Out There", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "God Help the Outcasts", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Hellfire", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "I Won't Say I'm in Love", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "The Gospel Truth", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Two Worlds", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Son of Man", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Trashin' the Camp", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "When She Loved Me", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Life is a Highway", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "Real Gone", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Touch the Sky", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Into the Open Air", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Speechless", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Show Yourself", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "The Next Right Thing", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Lost in the Woods", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Some Things Never Change", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Waiting on a Miracle", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "What Else Can I Do", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "The Family Madrigal", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Dos Oruguitas", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Dig a Little Deeper", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Down in New Orleans", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Almost There", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "When Will My Life Begin", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "I've Got a Dream", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Immortals", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Oo-De-Lally", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Not in Nottingham", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Goodbye May Seem Forever", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Best of Friends", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Perfect World", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "I2I", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Stand Out", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "On the Open Road", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "After Today", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Poor Jack", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "This Is Halloween", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Oogie Boogie's Song", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "What's This?", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Kidnap the Sandy Claws", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Grim Grinning Ghosts", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Yo Ho (A Pirate's Life for Me)", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "It's a Small World", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "The Tiki, Tiki, Tiki Room", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "There's a Great Big Beautiful Tomorrow", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Golden Dream", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Zip-a-Dee-Doo-Dah", "topic": "Disney Songs", "difficulty": "Medium" },

// --- ZOO & JUNGLE CHARACTERS (ADDITIONAL) ---
{ "word": "Kaa", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "King Louie", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Shere Khan", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Colonel Hathi", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Junior", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Winifred", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Akela", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Raksha", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Zira", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Kovu", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Kiara", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Nuka", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Vitani", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Janja", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Kion", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Bunga", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Fuli", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Beshte", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Ono", "topic": "Disney Characters", "difficulty": "Hard" },

// --- SPACE & SCI-FI (STAR WARS & MARVEL IN DISNEY PARKS) ---
{ "word": "Rey", "topic": "Disney Parks Characters", "difficulty": "Easy" },
{ "word": "Kylo Ren", "topic": "Disney Parks Characters", "difficulty": "Easy" },
{ "word": "BB-8", "topic": "Disney Parks Characters", "difficulty": "Easy" },
{ "word": "R2-D2", "topic": "Disney Parks Characters", "difficulty": "Easy" },
{ "word": "C-3PO", "topic": "Disney Parks Characters", "difficulty": "Easy" },
{ "word": "Chewbacca", "topic": "Disney Parks Characters", "difficulty": "Easy" },
{ "word": "Grogu", "topic": "Disney Parks Characters", "difficulty": "Easy" },
{ "word": "The Mandalorian", "topic": "Disney Parks Characters", "difficulty": "Medium" },
{ "word": "Ahsoka Tano", "topic": "Disney Parks Characters", "difficulty": "Medium" },
{ "word": "Darth Vader", "topic": "Disney Parks Characters", "difficulty": "Easy" },
{ "word": "Stormtrooper", "topic": "Disney Parks Characters", "difficulty": "Easy" },
{ "word": "Yoda", "topic": "Disney Parks Characters", "difficulty": "Easy" },
{ "word": "Spider-Man", "topic": "Disney Parks Characters", "difficulty": "Easy" },
{ "word": "Iron Man", "topic": "Disney Parks Characters", "difficulty": "Easy" },
{ "word": "Captain America", "topic": "Disney Parks Characters", "difficulty": "Easy" },
{ "word": "Black Panther", "topic": "Disney Parks Characters", "difficulty": "Medium" },
{ "word": "Groot", "topic": "Disney Parks Characters", "difficulty": "Easy" },
{ "word": "Rocket Raccoon", "topic": "Disney Parks Characters", "difficulty": "Medium" },
{ "word": "Thor", "topic": "Disney Parks Characters", "difficulty": "Medium" },
{ "word": "Loki", "topic": "Disney Parks Characters", "difficulty": "Medium" },
{ "word": "Black Widow", "topic": "Disney Parks Characters", "difficulty": "Medium" },
{ "word": "Hulk", "topic": "Disney Parks Characters", "difficulty": "Easy" },
{ "word": "Thanos", "topic": "Disney Parks Characters", "difficulty": "Medium" },
{ "word": "Doctor Strange", "topic": "Disney Parks Characters", "difficulty": "Medium" },
{ "word": "Ant-Man", "topic": "Disney Parks Characters", "difficulty": "Medium" },
{ "word": "Wasp", "topic": "Disney Parks Characters", "difficulty": "Medium" },
{ "word": "Captain Marvel", "topic": "Disney Parks Characters", "difficulty": "Medium" },

// --- VIDEO GAMES (KINGDOM HEARTS & OTHERS) ---
{ "word": "Sora", "topic": "Disney Video Games", "difficulty": "Hard" },
{ "word": "Riku", "topic": "Disney Video Games", "difficulty": "Hard" },
{ "word": "Kairi", "topic": "Disney Video Games", "difficulty": "Hard" },
{ "word": "Keyblade", "topic": "Disney Video Games", "difficulty": "Hard" },
{ "word": "Heartless", "topic": "Disney Video Games", "difficulty": "Hard" },
{ "word": "Organization XIII", "topic": "Disney Video Games", "difficulty": "Hard" },
{ "word": "Epic Mickey", "topic": "Disney Video Games", "difficulty": "Hard" },
{ "word": "Disney Infinity", "topic": "Disney Video Games", "difficulty": "Medium" },
{ "word": "Tsum Tsum", "topic": "Disney Video Games", "difficulty": "Medium" },

// --- BROADWAY & MUSICALS ---
{ "word": "Newsies", "topic": "Disney Musicals", "difficulty": "Hard" },
{ "word": "Jack Kelly", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Crutchie", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Katherine Plumber", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "The Lion King Musical", "topic": "Disney Musicals", "difficulty": "Medium" },
{ "word": "Aladdin Musical", "topic": "Disney Musicals", "difficulty": "Medium" },
{ "word": "Frozen Musical", "topic": "Disney Musicals", "difficulty": "Medium" },
{ "word": "Aida", "topic": "Disney Musicals", "difficulty": "Hard" },

// --- MICKEY & FRIENDS ---
{ "word": "Mickey Mouse", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Minnie Mouse", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Donald Duck", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Daisy Duck", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Goofy", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Pluto", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Chip", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Dale", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Clarabelle Cow", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Horace Horsecollar", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Pete", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Max Goof", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Scrooge McDuck", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Huey", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Dewey", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Louie", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Webby", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Launchpad McQuack", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Oswald", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Steamboat Willie", "topic": "Disney Movies", "difficulty": "Medium" },

// --- DISNEY PRINCESSES & HEROINES ---
{ "word": "Snow White", "topic": "Disney Princesses", "difficulty": "Easy" },
{ "word": "Cinderella", "topic": "Disney Princesses", "difficulty": "Easy" },
{ "word": "Aurora", "topic": "Disney Princesses", "difficulty": "Medium" },
{ "word": "Ariel", "topic": "Disney Princesses", "difficulty": "Easy" },
{ "word": "Belle", "topic": "Disney Princesses", "difficulty": "Easy" },
{ "word": "Jasmine", "topic": "Disney Princesses", "difficulty": "Easy" },
{ "word": "Pocahontas", "topic": "Disney Princesses", "difficulty": "Medium" },
{ "word": "Mulan", "topic": "Disney Princesses", "difficulty": "Easy" },
{ "word": "Tiana", "topic": "Disney Princesses", "difficulty": "Medium" },
{ "word": "Rapunzel", "topic": "Disney Princesses", "difficulty": "Easy" },
{ "word": "Merida", "topic": "Disney Princesses", "difficulty": "Medium" },
{ "word": "Moana", "topic": "Disney Princesses", "difficulty": "Easy" },
{ "word": "Elsa", "topic": "Disney Princesses", "difficulty": "Easy" },
{ "word": "Anna", "topic": "Disney Princesses", "difficulty": "Easy" },
{ "word": "Raya", "topic": "Disney Princesses", "difficulty": "Medium" },
{ "word": "Mirabel", "topic": "Disney Princesses", "difficulty": "Easy" },
{ "word": "Esmeralda", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Megara", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Jane", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Alice", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Wendy", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Tinker Bell", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Lilo", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Vanellope", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Kida", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Giselle", "topic": "Disney Characters", "difficulty": "Medium" },

// --- DISNEY PRINCES & HEROES ---
{ "word": "Aladdin", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Simba", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Beast", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Prince Charming", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Prince Eric", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Prince Philip", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Hercules", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Tarzan", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Quasimodo", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Kuzco", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Pacha", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Mowgli", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Peter Pan", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Robin Hood", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Flynn Rider", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Kristoff", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Li Shang", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Naveen", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "John Smith", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Arthur", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Milo Thatch", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Jim Hawkins", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Hiro Hamada", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Baymax", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Nick Wilde", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Maui", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Bruno", "topic": "Disney Characters", "difficulty": "Easy" },

// --- DISNEY VILLAINS ---
{ "word": "Evil Queen", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Maleficent", "topic": "Disney Villains", "difficulty": "Easy" },
{ "word": "Cruella de Vil", "topic": "Disney Villains", "difficulty": "Easy" },
{ "word": "Ursula", "topic": "Disney Villains", "difficulty": "Easy" },
{ "word": "Jafar", "topic": "Disney Villains", "difficulty": "Easy" },
{ "word": "Scar", "topic": "Disney Villains", "difficulty": "Easy" },
{ "word": "Hades", "topic": "Disney Villains", "difficulty": "Easy" },
{ "word": "Gaston", "topic": "Disney Villains", "difficulty": "Easy" },
{ "word": "Captain Hook", "topic": "Disney Villains", "difficulty": "Easy" },
{ "word": "Dr. Facilier", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Mother Gothel", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Lady Tremaine", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Queen of Hearts", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Yzma", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Kronk", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Hans", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Claude Frollo", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Shere Khan", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Kaa", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "King Candy", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Governor Ratcliffe", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Shan Yu", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Clayton", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Chernabog", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Prince John", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Madam Mim", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Medusa", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Tamatoa", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Oogie Boogie", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Sid Phillips", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Lotso", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Syndrome", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Randall Boggs", "topic": "Disney Villains", "difficulty": "Medium" },
{ "word": "Ernesto de la Cruz", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Hopper", "topic": "Disney Villains", "difficulty": "Hard" },
{ "word": "Zurg", "topic": "Disney Villains", "difficulty": "Medium" },

// --- SIDEKICKS & FRIENDS ---
{ "word": "Olaf", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Genie", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Mushu", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Timon", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Pumbaa", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Sebastian", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Flounder", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Lumiere", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Cogsworth", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Mrs. Potts", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Abu", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Iago", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Pascal", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Maximus", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Sven", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Heihei", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Pua", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Stitch", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Dory", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Jiminy Cricket", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Thumper", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Flower", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Baloo", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Bagheera", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Rafiki", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Zazu", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Pegasus", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Phil", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Meeko", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Flit", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Terk", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Tantor", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Louis", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Ray", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Seven Dwarfs", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Dopey", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Grumpy", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Doc", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Happy", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Bashful", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Sneezy", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Sleepy", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Cheshire Cat", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Mad Hatter", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "White Rabbit", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Fairy Godmother", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Jaq", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Gus", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Smee", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Scuttle", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Piglet", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Tigger", "topic": "Disney Characters", "difficulty": "Easy" },
{ "word": "Eeyore", "topic": "Disney Characters", "difficulty": "Medium" },
{ "word": "Roo", "topic": "Disney Characters", "difficulty": "Hard" },
{ "word": "Christopher Robin", "topic": "Disney Characters", "difficulty": "Medium" },

// --- PIXAR FAVORITES ---
{ "word": "Woody", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Buzz Lightyear", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Jessie", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Rex", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Hamm", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Slinky Dog", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Mr. Potato Head", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Bo Peep", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Forky", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Nemo", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Marlin", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Crush", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Squirt", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Mike Wazowski", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Sulley", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Boo", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Lightning McQueen", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Mater", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Sally", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Doc Hudson", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Mr. Incredible", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Elastigirl", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Violet", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Dash", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Jack-Jack", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Edna Mode", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Frozone", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Remy", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Linguini", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Emile", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Carl Fredricksen", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Russell", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Dug", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Kevin", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "WALL-E", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "EVE", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Miguel", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Hector", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Dante", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Mama Coco", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Joy", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Sadness", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Anger", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Fear", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Disgust", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Bing Bong", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Anxiety", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Ennui", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Luca", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Alberto", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Mei Lee", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Red Panda", "topic": "Pixar", "difficulty": "Easy" },
{ "word": "Joe Gardner", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "22", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Flik", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Dot", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Arlo", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Spot", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Ian Lightfoot", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Barley Lightfoot", "topic": "Pixar", "difficulty": "Hard" },
{ "word": "Ember", "topic": "Pixar", "difficulty": "Medium" },
{ "word": "Wade", "topic": "Pixar", "difficulty": "Medium" },

// --- DISNEY MOVIES (Titles) ---
{ "word": "The Lion King", "topic": "Disney Movies", "difficulty": "Easy" },
{ "word": "Aladdin", "topic": "Disney Movies", "difficulty": "Easy" },
{ "word": "Frozen", "topic": "Disney Movies", "difficulty": "Easy" },
{ "word": "Moana", "topic": "Disney Movies", "difficulty": "Easy" },
{ "word": "Encanto", "topic": "Disney Movies", "difficulty": "Easy" },
{ "word": "Tangled", "topic": "Disney Movies", "difficulty": "Easy" },
{ "word": "Zootopia", "topic": "Disney Movies", "difficulty": "Easy" },
{ "word": "Big Hero 6", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Beauty and the Beast", "topic": "Disney Movies", "difficulty": "Easy" },
{ "word": "The Little Mermaid", "topic": "Disney Movies", "difficulty": "Easy" },
{ "word": "Mulan", "topic": "Disney Movies", "difficulty": "Easy" },
{ "word": "Pocahontas", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Hercules", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Tarzan", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "The Jungle Book", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Peter Pan", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Alice in Wonderland", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Pinocchio", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Dumbo", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Bambi", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Fantasia", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "Lady and the Tramp", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "101 Dalmatians", "topic": "Disney Movies", "difficulty": "Easy" },
{ "word": "The Aristocats", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "Robin Hood", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "The Rescuers", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "The Fox and the Hound", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "The Great Mouse Detective", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "Oliver & Company", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "The Hunchback of Notre Dame", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "Brother Bear", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "Home on the Range", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "Chicken Little", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "Meet the Robinsons", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "Bolt", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Wreck-It Ralph", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Strange World", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "Wish", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Mary Poppins", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Hocus Pocus", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Pirates of the Caribbean", "topic": "Disney Movies", "difficulty": "Easy" },
{ "word": "Jungle Cruise", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Haunted Mansion", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "High School Musical", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Descendants", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Zombies", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Camp Rock", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Tron", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "National Treasure", "topic": "Disney Movies", "difficulty": "Hard" },
{ "word": "The Parent Trap", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Freaky Friday", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Princess Diaries", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Enchanted", "topic": "Disney Movies", "difficulty": "Medium" },
{ "word": "Disenchanted", "topic": "Disney Movies", "difficulty": "Hard" },

// --- DISNEY SONGS ---
{ "word": "Let It Go", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "A Whole New World", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "Circle of Life", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "Hakuna Matata", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "Under the Sea", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "Part of Your World", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "Be Our Guest", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Beauty and the Beast", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Colors of the Wind", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Reflection", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "I'll Make a Man Out of You", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Go the Distance", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "You'll Be in My Heart", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "You've Got a Friend in Me", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "When You Wish Upon a Star", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Bare Necessities", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Supercalifragilistic", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Spoonful of Sugar", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "How Far I'll Go", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "You're Welcome", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Shiny", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "We Don't Talk About Bruno", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "Surface Pressure", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Into the Unknown", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Do You Want to Build a Snowman", "topic": "Disney Songs", "difficulty": "Easy" },
{ "word": "Love is an Open Door", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "I See the Light", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Almost There", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Friends on the Other Side", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Poor Unfortunate Souls", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Gaston", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Be Prepared", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Mother Knows Best", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Remember Me", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Un Poco Loco", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Try Everything", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Hawaiian Roller Coaster Ride", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "I Just Can't Wait to Be King", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Bibbidi-Bobbidi-Boo", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Heigh-Ho", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Whistle While You Work", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Baby Mine", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Cruella de Vil", "topic": "Disney Songs", "difficulty": "Medium" },
{ "word": "Ev'rybody Wants to Be a Cat", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Why Should I Worry", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Zero to Hero", "topic": "Disney Songs", "difficulty": "Hard" },
{ "word": "Strangers Like Me", "topic": "Disney Songs", "difficulty": "Hard" },

// --- LOCATIONS, PARKS & ITEMS ---
{ "word": "Disney World", "topic": "Disney Parks", "difficulty": "Easy" },
{ "word": "Disneyland", "topic": "Disney Parks", "difficulty": "Easy" },
{ "word": "Magic Kingdom", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Epcot", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Animal Kingdom", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Hollywood Studios", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Cinderella Castle", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Space Mountain", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Splash Mountain", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Big Thunder Mountain", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Haunted Mansion", "topic": "Disney Parks", "difficulty": "Easy" },
{ "word": "Pirates of the Caribbean", "topic": "Disney Parks", "difficulty": "Easy" },
{ "word": "It's a Small World", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Jungle Cruise", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Tower of Terror", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Main Street USA", "topic": "Disney Parks", "difficulty": "Hard" },
{ "word": "Tomorrowland", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Fantasyland", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Adventureland", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Frontierland", "topic": "Disney Parks", "difficulty": "Medium" },
{ "word": "Arendelle", "topic": "Disney Locations", "difficulty": "Medium" },
{ "word": "Agrabah", "topic": "Disney Locations", "difficulty": "Medium" },
{ "word": "Atlantica", "topic": "Disney Locations", "difficulty": "Medium" },
{ "word": "Pride Rock", "topic": "Disney Locations", "difficulty": "Medium" },
{ "word": "Neverland", "topic": "Disney Locations", "difficulty": "Easy" },
{ "word": "Wonderland", "topic": "Disney Locations", "difficulty": "Easy" },
{ "word": "Olympus", "topic": "Disney Locations", "difficulty": "Medium" },
{ "word": "Motunui", "topic": "Disney Locations", "difficulty": "Hard" },
{ "word": "Zootopia", "topic": "Disney Locations", "difficulty": "Easy" },
{ "word": "Radiator Springs", "topic": "Disney Locations", "difficulty": "Medium" },
{ "word": "Andy's Room", "topic": "Disney Locations", "difficulty": "Medium" },
{ "word": "Monstropolis", "topic": "Disney Locations", "difficulty": "Hard" },
{ "word": "Hundred Acre Wood", "topic": "Disney Locations", "difficulty": "Medium" },
{ "word": "Glass Slipper", "topic": "Disney Items", "difficulty": "Easy" },
{ "word": "Magic Lamp", "topic": "Disney Items", "difficulty": "Easy" },
{ "word": "Magic Carpet", "topic": "Disney Items", "difficulty": "Easy" },
{ "word": "Poison Apple", "topic": "Disney Items", "difficulty": "Medium" },
{ "word": "Spinning Wheel", "topic": "Disney Items", "difficulty": "Medium" },
{ "word": "Dinglehopper", "topic": "Disney Items", "difficulty": "Hard" },
{ "word": "Snuggly Duckling", "topic": "Disney Locations", "difficulty": "Hard" },
{ "word": "Frying Pan", "topic": "Disney Items", "difficulty": "Medium" },
{ "word": "Genie's Lamp", "topic": "Disney Items", "difficulty": "Easy" },
{ "word": "Pixie Dust", "topic": "Disney Items", "difficulty": "Medium" },
{ "word": "Hook's Hook", "topic": "Disney Items", "difficulty": "Medium" },
{ "word": "Sorcerer's Hat", "topic": "Disney Items", "difficulty": "Medium" },
{ "word": "Mickey Ears", "topic": "Disney Items", "difficulty": "Easy" },
{ "word": "Churro", "topic": "Disney Food", "difficulty": "Medium" },
{ "word": "Dole Whip", "topic": "Disney Food", "difficulty": "Hard" },
{ "word": "Mickey Bar", "topic": "Disney Food", "difficulty": "Medium" },
{ "word": "Grey Stuff", "topic": "Disney Food", "difficulty": "Hard" },
{ "word": "Beignet", "topic": "Disney Food", "difficulty": "Hard" },
{ "word": "Ratatouille", "topic": "Disney Food", "difficulty": "Easy" },
{ "word": "Hunny Pot", "topic": "Disney Items", "difficulty": "Medium" },
{ "word": "Rose", "topic": "Disney Items", "difficulty": "Easy" },
{ "word": "Mirror", "topic": "Disney Items", "difficulty": "Medium" },
{ "word": "Pumpkin Carriage", "topic": "Disney Items", "difficulty": "Medium" },
{ "word": "Ice Palace", "topic": "Disney Locations", "difficulty": "Medium" },
{ "word": "Casita", "topic": "Disney Locations", "difficulty": "Medium" },
{ "word": "Candle", "topic": "Disney Items", "difficulty": "Medium" },
{ "word": "Heart of Te Fiti", "topic": "Disney Items", "difficulty": "Hard" },
{ "word": "Ohana", "topic": "Disney Words", "difficulty": "Easy" }
];
