window.w = [
{ "word": "Dog", "topic": "Animals", "difficulty": "Easy" },
{ "word": "Cat", "topic": "Animals", "difficulty": "Easy" },
{ "word": "Fish", "topic": "Animals", "difficulty": "Easy" },
{ "word": "Bird", "topic": "Animals", "difficulty": "Easy" },
{ "word": "Lion", "topic": "Animals", "difficulty": "Easy" },
{ "word": "Tiger", "topic": "Animals", "difficulty": "Easy" },
{ "word": "Bear", "topic": "Animals", "difficulty": "Easy" },
{ "word": "Horse", "topic": "Animals", "difficulty": "Easy" },
{ "word": "Cow", "topic": "Animals", "difficulty": "Easy" },
{ "word": "Pig", "topic": "Animals", "difficulty": "Easy" },
{ "word": "Elephant", "topic": "Animals", "difficulty": "Medium" },
{ "word": "Giraffe", "topic": "Animals", "difficulty": "Medium" },
{ "word": "Zebra", "topic": "Animals", "difficulty": "Medium" },
{ "word": "Monkey", "topic": "Animals", "difficulty": "Medium" },
{ "word": "Kangaroo", "topic": "Animals", "difficulty": "Medium" },
{ "word": "Penguin", "topic": "Animals", "difficulty": "Medium" },
{ "word": "Dolphin", "topic": "Animals", "difficulty": "Medium" },
{ "word": "Shark", "topic": "Animals", "difficulty": "Medium" },
{ "word": "Whale", "topic": "Animals", "difficulty": "Medium" },
{ "word": "Octopus", "topic": "Animals", "difficulty": "Medium" },
{ "word": "Platypus", "topic": "Animals", "difficulty": "Hard" },
{ "word": "Narwhal", "topic": "Animals", "difficulty": "Hard" },
{ "word": "Axolotl", "topic": "Animals", "difficulty": "Hard" },
{ "word": "Chameleon", "topic": "Animals", "difficulty": "Hard" },
{ "word": "Armadillo", "topic": "Animals", "difficulty": "Hard" },
{ "word": "Porcupine", "topic": "Animals", "difficulty": "Hard" },
{ "word": "Meerkat", "topic": "Animals", "difficulty": "Hard" },
{ "word": "Lemur", "topic": "Animals", "difficulty": "Hard" },
{ "word": "Hippopotamus", "topic": "Animals", "difficulty": "Hard" },
{ "word": "Rhinoceros", "topic": "Animals", "difficulty": "Hard" },

{ "word": "Apple", "topic": "Food", "difficulty": "Easy" },
{ "word": "Banana", "topic": "Food", "difficulty": "Easy" },
{ "word": "Grape", "topic": "Food", "difficulty": "Easy" },
{ "word": "Orange", "topic": "Food", "difficulty": "Easy" },
{ "word": "Pizza", "topic": "Food", "difficulty": "Easy" },
{ "word": "Burger", "topic": "Food", "difficulty": "Easy" },
{ "word": "Fries", "topic": "Food", "difficulty": "Easy" },
{ "word": "Cake", "topic": "Food", "difficulty": "Easy" },
{ "word": "Cookie", "topic": "Food", "difficulty": "Easy" },
{ "word": "Ice Cream", "topic": "Food", "difficulty": "Easy" },
{ "word": "Bread", "topic": "Food", "difficulty": "Easy" },
{ "word": "Cheese", "topic": "Food", "difficulty": "Easy" },
{ "word": "Egg", "topic": "Food", "difficulty": "Easy" },
{ "word": "Milk", "topic": "Food", "difficulty": "Easy" },
{ "word": "Water", "topic": "Food", "difficulty": "Easy" },
{ "word": "Carrot", "topic": "Food", "difficulty": "Easy" },
{ "word": "Potato", "topic": "Food", "difficulty": "Easy" },
{ "word": "Tomato", "topic": "Food", "difficulty": "Easy" },
{ "word": "Onion", "topic": "Food", "difficulty": "Easy" },
{ "word": "Garlic", "topic": "Food", "difficulty": "Easy" },
{ "word": "Spaghetti", "topic": "Food", "difficulty": "Medium" },
{ "word": "Sushi", "topic": "Food", "difficulty": "Medium" },
{ "word": "Salad", "topic": "Food", "difficulty": "Medium" },
{ "word": "Sandwich", "topic": "Food", "difficulty": "Medium" },
{ "word": "Pancake", "topic": "Food", "difficulty": "Medium" },
{ "word": "Waffle", "topic": "Food", "difficulty": "Medium" },
{ "word": "Taco", "topic": "Food", "difficulty": "Medium" },
{ "word": "Burrito", "topic": "Food", "difficulty": "Medium" },
{ "word": "Steak", "topic": "Food", "difficulty": "Medium" },
{ "word": "Chicken", "topic": "Food", "difficulty": "Medium" },
{ "word": "Soup", "topic": "Food", "difficulty": "Medium" },
{ "word": "Rice", "topic": "Food", "difficulty": "Medium" },
{ "word": "Noodles", "topic": "Food", "difficulty": "Medium" },
{ "word": "Curry", "topic": "Food", "difficulty": "Medium" },
{ "word": "Dumpling", "topic": "Food", "difficulty": "Medium" },
{ "word": "Kebab", "topic": "Food", "difficulty": "Medium" },
{ "word": "Falafel", "topic": "Food", "difficulty": "Medium" },
{ "word": "Hummus", "topic": "Food", "difficulty": "Medium" },
{ "word": "Quinoa", "topic": "Food", "difficulty": "Medium" },
{ "word": "Lentils", "topic": "Food", "difficulty": "Medium" },
{ "word": "Croissant", "topic": "Food", "difficulty": "Hard" },
{ "word": "Lasagna", "topic": "Food", "difficulty": "Hard" },
{ "word": "Guacamole", "topic": "Food", "difficulty": "Hard" },
{ "word": "Quesadilla", "topic": "Food", "difficulty": "Hard" },
{ "word": "Pomegranate", "topic": "Food", "difficulty": "Hard" },
{ "word": "Asparagus", "topic": "Food", "difficulty": "Hard" },
{ "word": "Cauliflower", "topic": "Food", "difficulty": "Hard" },
{ "word": "Zucchini", "topic": "Food", "difficulty": "Hard" },
{ "word": "Artichoke", "topic": "Food", "difficulty": "Hard" },
{ "word": "Goulash", "topic": "Food", "difficulty": "Hard" },
{ "word": "Kimchi", "topic": "Food", "difficulty": "Hard" },
{ "word": "Paella", "topic": "Food", "difficulty": "Hard" },
{ "word": "Ratatouille", "topic": "Food", "difficulty": "Hard" },
{ "word": "Escargot", "topic": "Food", "difficulty": "Hard" },
{ "word": "Truffle", "topic": "Food", "difficulty": "Hard" },
{ "word": "Saffron", "topic": "Food", "difficulty": "Hard" },

{ "word": "Soccer", "topic": "Sports", "difficulty": "Easy" },
{ "word": "Basketball", "topic": "Sports", "difficulty": "Easy" },
{ "word": "Baseball", "topic": "Sports", "difficulty": "Easy" },
{ "word": "Football", "topic": "Sports", "difficulty": "Easy" },
{ "word": "Tennis", "topic": "Sports", "difficulty": "Easy" },
{ "word": "Golf", "topic": "Sports", "difficulty": "Easy" },
{ "word": "Running", "topic": "Sports", "difficulty": "Easy" },
{ "word": "Swimming", "topic": "Sports", "difficulty": "Easy" },
{ "word": "Dancing", "topic": "Sports", "difficulty": "Easy" },
{ "word": "Skiing", "topic": "Sports", "difficulty": "Easy" },
{ "word": "Volleyball", "topic": "Sports", "difficulty": "Medium" },
{ "word": "Hockey", "topic": "Sports", "difficulty": "Medium" },
{ "word": "Boxing", "topic": "Sports", "difficulty": "Medium" },
{ "word": "Karate", "topic": "Sports", "difficulty": "Medium" },
{ "word": "Surfing", "topic": "Sports", "difficulty": "Medium" },
{ "word": "Skating", "topic": "Sports", "difficulty": "Medium" },
{ "word": "Cycling", "topic": "Sports", "difficulty": "Medium" },
{ "word": "Bowling", "topic": "Sports", "difficulty": "Medium" },
{ "word": "Gymnastics", "topic": "Sports", "difficulty": "Medium" },
{ "word": "Wrestling", "topic": "Sports", "difficulty": "Medium" },
{ "word": "Badminton", "topic": "Sports", "difficulty": "Hard" },
{ "word": "Cricket", "topic": "Sports", "difficulty": "Hard" },
{ "word": "Rugby", "topic": "Sports", "difficulty": "Hard" },
{ "word": "Lacrosse", "topic": "Sports", "difficulty": "Hard" },
{ "word": "Fencing", "topic": "Sports", "difficulty": "Hard" },
{ "word": "Archery", "topic": "Sports", "difficulty": "Hard" },
{ "word": "Snowboarding", "topic": "Sports", "difficulty": "Hard" },
{ "word": "Skateboarding", "topic": "Sports", "difficulty": "Hard" },
{ "word": "Triathlon", "topic": "Sports", "difficulty": "Hard" },
{ "word": "Water Polo", "topic": "Sports", "difficulty": "Hard" },

{ "word": "Chair", "topic": "Household", "difficulty": "Easy" },
{ "word": "Table", "topic": "Household", "difficulty": "Easy" },
{ "word": "Bed", "topic": "Household", "difficulty": "Easy" },
{ "word": "Door", "topic": "Household", "difficulty": "Easy" },
{ "word": "Window", "topic": "Household", "difficulty": "Easy" },
{ "word": "Spoon", "topic": "Household", "difficulty": "Easy" },
{ "word": "Fork", "topic": "Household", "difficulty": "Easy" },
{ "word": "Cup", "topic": "Household", "difficulty": "Easy" },
{ "word": "Plate", "topic": "Household", "difficulty": "Easy" },
{ "word": "Lamp", "topic": "Household", "difficulty": "Easy" },
{ "word": "Sofa", "topic": "Household", "difficulty": "Medium" },
{ "word": "Fridge", "topic": "Household", "difficulty": "Medium" },
{ "word": "Oven", "topic": "Household", "difficulty": "Medium" },
{ "word": "Toaster", "topic": "Household", "difficulty": "Medium" },
{ "word": "Blender", "topic": "Household", "difficulty": "Medium" },
{ "word": "Mirror", "topic": "Household", "difficulty": "Medium" },
{ "word": "Towel", "topic": "Household", "difficulty": "Medium" },
{ "word": "Pillow", "topic": "Household", "difficulty": "Medium" },
{ "word": "Blanket", "topic": "Household", "difficulty": "Medium" },
{ "word": "Clock", "topic": "Household", "difficulty": "Medium" },
{ "word": "Microwave", "topic": "Household", "difficulty": "Hard" },
{ "word": "Dishwasher", "topic": "Household", "difficulty": "Hard" },
{ "word": "Vacuum", "topic": "Household", "difficulty": "Hard" },
{ "word": "Bookshelf", "topic": "Household", "difficulty": "Hard" },
{ "word": "Wardrobe", "topic": "Household", "difficulty": "Hard" },
{ "word": "Fireplace", "topic": "Household", "difficulty": "Hard" },
{ "word": "Chandelier", "topic": "Household", "difficulty": "Hard" },
{ "word": "Thermostat", "topic": "Household", "difficulty": "Hard" },
{ "word": "Colander", "topic": "Household", "difficulty": "Hard" },
{ "word": "Spatula", "topic": "Household", "difficulty": "Hard" },

{ "word": "Tree", "topic": "Nature", "difficulty": "Easy" },
{ "word": "Flower", "topic": "Nature", "difficulty": "Easy" },
{ "word": "Sun", "topic": "Nature", "difficulty": "Easy" },
{ "word": "Moon", "topic": "Nature", "difficulty": "Easy" },
{ "word": "Star", "topic": "Nature", "difficulty": "Easy" },
{ "word": "Cloud", "topic": "Nature", "difficulty": "Easy" },
{ "word": "Rain", "topic": "Nature", "difficulty": "Easy" },
{ "word": "Snow", "topic": "Nature", "difficulty": "Easy" },
{ "word": "Grass", "topic": "Nature", "difficulty": "Easy" },
{ "word": "Rock", "topic": "Nature", "difficulty": "Easy" },
{ "word": "Mountain", "topic": "Nature", "difficulty": "Medium" },
{ "word": "River", "topic": "Nature", "difficulty": "Medium" },
{ "word": "Ocean", "topic": "Nature", "difficulty": "Medium" },
{ "word": "Forest", "topic": "Nature", "difficulty": "Medium" },
{ "word": "Desert", "topic": "Nature", "difficulty": "Medium" },
{ "word": "Beach", "topic": "Nature", "difficulty": "Medium" },
{ "word": "Island", "topic": "Nature", "difficulty": "Medium" },
{ "word": "Volcano", "topic": "Nature", "difficulty": "Medium" },
{ "word": "Rainbow", "topic": "Nature", "difficulty": "Medium" },
{ "word": "Thunder", "topic": "Nature", "difficulty": "Medium" },
{ "word": "Nature", "topic": "Nature", "difficulty": "Medium" },
{ "word": "Waterfall", "topic": "Nature", "difficulty": "Hard" },
{ "word": "Hurricane", "topic": "Nature", "difficulty": "Hard" },
{ "word": "Tornado", "topic": "Nature", "difficulty": "Hard" },
{ "word": "Earthquake", "topic": "Nature", "difficulty": "Hard" },
{ "word": "Glacier", "topic": "Nature", "difficulty": "Hard" },
{ "word": "Canyon", "topic": "Nature", "difficulty": "Hard" },
{ "word": "Jungle", "topic": "Nature", "difficulty": "Hard" },
{ "word": "Swamp", "topic": "Nature", "difficulty": "Hard" },
{ "word": "Tundra", "topic": "Nature", "difficulty": "Hard" },
{ "word": "Meteor", "topic": "Nature", "difficulty": "Hard" },

{ "word": "Doctor", "topic": "Occupations", "difficulty": "Easy" },
{ "word": "Teacher", "topic": "Occupations", "difficulty": "Easy" },
{ "word": "Cop", "topic": "Occupations", "difficulty": "Easy" },
{ "word": "Cook", "topic": "Occupations", "difficulty": "Easy" },
{ "word": "Farmer", "topic": "Occupations", "difficulty": "Easy" },
{ "word": "Artist", "topic": "Occupations", "difficulty": "Easy" },
{ "word": "Singer", "topic": "Occupations", "difficulty": "Easy" },
{ "word": "Driver", "topic": "Occupations", "difficulty": "Easy" },
{ "word": "Nurse", "topic": "Occupations", "difficulty": "Easy" },
{ "word": "Pilot", "topic": "Occupations", "difficulty": "Easy" },
{ "word": "Firefighter", "topic": "Occupations", "difficulty": "Medium" },
{ "word": "Scientist", "topic": "Occupations", "difficulty": "Medium" },
{ "word": "Astronaut", "topic": "Occupations", "difficulty": "Medium" },
{ "word": "Dentist", "topic": "Occupations", "difficulty": "Medium" },
{ "word": "Plumber", "topic": "Occupations", "difficulty": "Medium" },
{ "word": "Mechanic", "topic": "Occupations", "difficulty": "Medium" },
{ "word": "Writer", "topic": "Occupations", "difficulty": "Medium" },
{ "word": "Actor", "topic": "Occupations", "difficulty": "Medium" },
{ "word": "Judge", "topic": "Occupations", "difficulty": "Medium" },
{ "word": "Baker", "topic": "Occupations", "difficulty": "Medium" },
{ "word": "Architect", "topic": "Occupations", "difficulty": "Hard" },
{ "word": "Engineer", "topic": "Occupations", "difficulty": "Hard" },
{ "word": "Surgeon", "topic": "Occupations", "difficulty": "Hard" },
{ "word": "Veterinarian", "topic": "Occupations", "difficulty": "Hard" },
{ "word": "Librarian", "topic": "Occupations", "difficulty": "Hard" },
{ "word": "Electrician", "topic": "Occupations", "difficulty": "Hard" },
{ "word": "Carpenter", "topic": "Occupations", "difficulty": "Hard" },
{ "word": "Journalist", "topic": "Occupations", "difficulty": "Hard" },
{ "word": "Politician", "topic": "Occupations", "difficulty": "Hard" },
{ "word": "Magician", "topic": "Occupations", "difficulty": "Hard" },
{ "word": "Chef", "topic": "Occupations", "difficulty": "Easy" },
{ "word": "Waiter", "topic": "Occupations", "difficulty": "Easy" },
{ "word": "Cashier", "topic": "Occupations", "difficulty": "Easy" },
{ "word": "Cleaner", "topic": "Occupations", "difficulty": "Easy" },
{ "word": "Guard", "topic": "Occupations", "difficulty": "Easy" },
{ "word": "Secretary", "topic": "Occupations", "difficulty": "Medium" },
{ "word": "Analyst", "topic": "Occupations", "difficulty": "Medium" },
{ "word": "Consultant", "topic": "Occupations", "difficulty": "Medium" },
{ "word": "Designer", "topic": "Occupations", "difficulty": "Medium" },
{ "word": "Programmer", "topic": "Occupations", "difficulty": "Medium" },
{ "word": "Accountant", "topic": "Occupations", "difficulty": "Hard" },
{ "word": "Geologist", "topic": "Occupations", "difficulty": "Hard" },
{ "word": "Biologist", "topic": "Occupations", "difficulty": "Hard" },
{ "word": "Chemist", "topic": "Occupations", "difficulty": "Hard" },
{ "word": "Physicist", "topic": "Occupations", "difficulty": "Hard" },

{ "word": "Run", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Jump", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Sleep", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Eat", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Drink", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Cry", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Laugh", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Walk", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Read", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Write", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Talk", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Listen", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Look", "topic": "Actions", "difficulty": "Easy" },
{ "word": "See", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Hear", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Smell", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Touch", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Taste", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Think", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Learn", "topic": "Actions", "difficulty": "Easy" },
{ "word": "Dance", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Sing", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Swim", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Climb", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Drive", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Cook", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Paint", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Throw", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Catch", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Kick", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Build", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Repair", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Clean", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Organize", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Travel", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Explore", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Create", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Imagine", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Solve", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Discover", "topic": "Actions", "difficulty": "Medium" },
{ "word": "Whistle", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Whisper", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Juggle", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Meditate", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Exercise", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Investigate", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Calculate", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Negotiate", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Navigate", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Celebrate", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Communicate", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Collaborate", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Innovate", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Strategize", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Synthesize", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Analyze", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Critique", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Develop", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Implement", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Optimize", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Facilitate", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Motivate", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Inspire", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Educate", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Mentor", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Supervise", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Manage", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Lead", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Direct", "topic": "Actions", "difficulty": "Hard" },
{ "word": "Coordinate", "topic": "Actions", "difficulty": "Hard" },

{ "word": "Frozen", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Cars", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Shrek", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Moana", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Coco", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Up", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Elf", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Finding Nemo", "topic": "Movies", "difficulty": "Kids" },
{ "word": "The Lion King", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Aladdin", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Toy Story", "topic": "Movies", "difficulty": "Kids" },
{ "word": "The Incredibles", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Ratatouille", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Wall-E", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Inside Out", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Zootopia", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Soul", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Luca", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Turning Red", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Encanto", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Kung Fu Panda", "topic": "Movies", "difficulty": "Kids" },
{ "word": "How to Train Your Dragon", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Madagascar", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Despicable Me", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Minions", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Sing", "topic": "Movies", "difficulty": "Kids" },
{ "word": "The Secret Life of Pets", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Tangled", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Brave", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Monsters Inc", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Spider-Man: Into the Spider-Verse", "topic": "Movies", "difficulty": "Kids" },
{ "word": "The Lego Movie", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Paddington", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Klaus", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Mitchells vs. the Machines", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Sing 2", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Puss in Boots: The Last Wish", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Elemental", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Super Mario Bros. Movie", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Migration", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Wish", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Trolls Band Together", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Paw Patrol: The Mighty Movie", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Teenage Mutant Ninja Turtles: Mutant Mayhem", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Ruby Gillman, Teenage Kraken", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Spider-Man: Across the Spider-Verse", "topic": "Movies", "difficulty": "Kids" },
{ "word": "The Little Mermaid (2023)", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Peter Pan & Wendy", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Shazam! Fury of the Gods", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Ant-Man and the Wasp: Quantumania", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Strange World", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Lightyear", "topic": "Movies", "difficulty": "Kids" },
{ "word": "DC League of Super-Pets", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Minions: The Rise of Gru", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Sonic the Hedgehog 2", "topic": "Movies", "difficulty": "Kids" },
{ "word": "The Bad Guys", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Raya and the Last Dragon", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Tom & Jerry", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Croods: A New Age", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Onward", "topic": "Movies", "difficulty": "Kids" },
{ "word": "Scoob!", "topic": "Movies", "difficulty": "Kids" },

{ "word": "Avatar", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Titanic", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Jaws", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Rocky", "topic": "Movies", "difficulty": "Adults" },
{ "word": "The Matrix", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Inception", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Gladiator", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Alien", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Speed", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Grease", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Parasite", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Memento", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Psycho", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Vertigo", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Casablanca", "topic": "Movies", "difficulty": "Adults" },
{ "word": "The Godfather", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Amadeus", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Chinatown", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Fargo", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Interstellar", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Forrest Gump", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Jurassic Park", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Back to the Future", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Star Wars", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Indiana Jones", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Dune", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Oppenheimer", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Barbie", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Top Gun: Maverick", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Everything Everywhere All at Once", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Spider-Man: No Way Home", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Dune: Part Two", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Napoleon", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Mission: Impossible - Dead Reckoning Part One", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Guardians of the Galaxy Vol. 3", "topic": "Movies", "difficulty": "Adults" },
{ "word": "John Wick: Chapter 4", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Creed III", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Cocaine Bear", "topic": "Movies", "difficulty": "Adults" },
{ "word": "M3GAN", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Glass Onion: A Knives Out Mystery", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Tár", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Black Panther: Wakanda Forever", "topic": "Movies", "difficulty": "Adults" },
{ "word": "Doctor Strange in the Multiverse of Madness", "topic": "Movies", "difficulty": "Adults" },
{ "word": "The Batman", "topic": "Movies", "difficulty": "Adults" },
{ "word": "West Side Story (2021)", "topic": "Movies", "difficulty": "Adults" },

{ "word": "Shirt", "topic": "Clothing", "difficulty": "Easy" },
{ "word": "Pants", "topic": "Clothing", "difficulty": "Easy" },
{ "word": "Hat", "topic": "Clothing", "difficulty": "Easy" },
{ "word": "Shoes", "topic": "Clothing", "difficulty": "Easy" },
{ "word": "Socks", "topic": "Clothing", "difficulty": "Easy" },
{ "word": "Dress", "topic": "Clothing", "difficulty": "Medium" },
{ "word": "Skirt", "topic": "Clothing", "difficulty": "Medium" },
{ "word": "Jacket", "topic": "Clothing", "difficulty": "Medium" },
{ "word": "Scarf", "topic": "Clothing", "difficulty": "Medium" },
{ "word": "Gloves", "topic": "Clothing", "difficulty": "Medium" },

{ "word": "Dragon", "topic": "Fantasy", "difficulty": "Easy" },
{ "word": "Wizard", "topic": "Fantasy", "difficulty": "Easy" },
{ "word": "Ghost", "topic": "Fantasy", "difficulty": "Easy" },
{ "word": "Unicorn", "topic": "Fantasy", "difficulty": "Medium" },
{ "word": "Mermaid", "topic": "Fantasy", "difficulty": "Medium" },
{ "word": "Vampire", "topic": "Fantasy", "difficulty": "Medium" },
{ "word": "Werewolf", "topic": "Fantasy", "difficulty": "Hard" },
{ "word": "Phoenix", "topic": "Fantasy", "difficulty": "Hard" },
{ "word": "Griffin", "topic": "Fantasy", "difficulty": "Hard" },

{ "word": "Dirt", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Stone", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Wood", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Sand", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Gravel", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Coal", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Iron", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Gold", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Diamond", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Emerald", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Redstone", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Lapis", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Torch", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Chest", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Furnace", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Bed", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Door", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Glass", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Wool", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Stick", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Sword", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Pickaxe", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Axe", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Shovel", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Hoe", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Apple", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Bread", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Steak", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Porkchop", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Chicken", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "TNT", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Bow", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Armor", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Shield", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Bucket", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Egg", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Milk", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Seed", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Kelp", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Rose", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Fish", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Cake", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Obsidian", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Bedrock", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Netherrack", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Soul Sand", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Glowstone", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Quartz", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "End Stone", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Purpur", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Prismarine", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Sponge", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Slime", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Piston", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Dispenser", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Dropper", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Observer", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Hopper", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Beacon", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Anvil", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Enchanting Table", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Brewing Stand", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Cauldron", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Lectern", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Composter", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Barrel", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Smoker", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Blast Furnace", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Cartography Table", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Fletching Table", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Grindstone", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Smithing Table", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Stonecutter", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Loom", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Compass", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Saddle", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Name Tag", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Repeater", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Comparator", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Daylight Sensor", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Redstone Dust", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Jukebox", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Trapped Chest", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Scaffolding", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Elytra", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Trident", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Totem", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Conduit", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Shulker Box", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Ender Chest", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Dragon Egg", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Nether Star", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Wither Skull", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Heart of the Sea", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Nautilus Shell", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Scute", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Phantom Membrane", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Rabbit Foot", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Ghast Tear", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Blaze Rod", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Magma Cream", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Nether Wart", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Chorus Fruit", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "End Rod", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Dragon Breath", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Respawn Anchor", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Lodestone", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Crying Obsidian", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Ancient Debris", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Netherite Ingot", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Spyglass", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Amethyst Shard", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Copper Ingot", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Lightning Rod", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Sculk Sensor", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Warden Heart", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Echo Shard", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Recovery Compass", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Disc Fragment", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Goat Horn", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Froglight", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Tadpole Bucket", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Allay", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Vex", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Ravager", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Pillager", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Evoker", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Vindicator", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Illusioner", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Witch", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Stray", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Husk", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Drowned", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Phantom", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Shulker", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Endermite", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Silverfish", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Command Block", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Structure Block", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Barrier", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Light Block", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Jigsaw Block", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Debug Stick", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Knowledge Book", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Bundle", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Brush", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Pottery Sherd", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Sniffer Egg", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Torchflower", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Pitcher Plant", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Calibrated Sculk", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Chiseled Bookshelf", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Hanging Sign", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Bamboo Raft", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Camel", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Sniffer", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Breeze", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Wind Charge", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Trial Key", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Ominous Bottle", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Crafter", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Copper Bulb", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Tuff", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Mace", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Heavy Core", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Breeze Rod", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Flow Banner", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Guster Banner", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Scrape Pottery", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Glazed Terracotta", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Budding Amethyst", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Gilded Blackstone", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Suspicious Gravel", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Calibrated Sensor", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "ME Controller", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Smeltery Grout", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Lexica Botania", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Atomic Reconstructor", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Sacrificial Dagger", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Flux Capacitor", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Crystal Growth Accelerator", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Nano Saber", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Digital Miner", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Mana Spreader", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Smithing Template", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Lingering Potion", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Petrified Oak Slab", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Potion of Leaping", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Music Disc 5", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Infested Deepslate", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Dragon's Breath", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Steve", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Alex", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Creeper", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Zombie", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Skeleton", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Spider", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Pig", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Cow", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Sheep", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Wolf", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Cat", "topic": "Minecraft", "difficulty": "Easy" },
{ "word": "Enderman", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Ghast", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Blaze", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Villager", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Iron Golem", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Piglin", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Guardian", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Horse", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Bee", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Axolotl", "topic": "Minecraft", "difficulty": "Medium" },
{ "word": "Warden", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Wither", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Ender Dragon", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Elder Guardian", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Bogged", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Creaking", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Hoglin", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Strider", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Herobrine", "topic": "Minecraft", "difficulty": "Hard" },
{ "word": "Mooshroom", "topic": "Minecraft", "difficulty": "Medium" }
];
