window.w = [
// --- INSTRUMENTS ---
{ "word": "Guitar", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Piano", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Drums", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Violin", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Trumpet", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Saxophone", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Clarinet", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Trombone", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Flute", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Cello", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Recorder", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Xylophone", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Tuba", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Harp", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Oboe", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Bassoon", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Banjo", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Ukulele", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Mandolin", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "French Horn", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Synthesizer", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Bagpipes", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Theremin", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Didgeridoo", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Harmonica", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Accordion", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Bass Guitar", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Electric Guitar", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Acoustic Guitar", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Keyboard", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Organ", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Pipe Organ", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Harpsichord", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Viola", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Double Bass", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Upright Bass", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Piccolo", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Kazoo", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Ocarina", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Panpipes", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Tin Whistle", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Melodica", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Concertina", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Dulcimer", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Zither", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Sitar", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Koto", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Shamisen", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Balalaika", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Lute", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Lyre", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Autoharp", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Pedal Steel Guitar", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Lap Steel Guitar", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Bouzouki", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Charango", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Cuatro", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Cittern", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "English Horn", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Cor Anglais", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Contrabassoon", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Bass Clarinet", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Soprano Saxophone", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Alto Saxophone", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Tenor Saxophone", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Baritone Saxophone", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Cornet", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Flugelhorn", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Euphonium", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Sousaphone", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Bugle", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Alphorn", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Shofar", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Conch Shell", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Vuvuzela", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Whistle", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Slide Whistle", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Jaw Harp", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Kalimba", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Mbira", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Steel Drums", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Hang Drum", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Tabla", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Djembe", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Cajon", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Bodhrán", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Taiko", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Darbuka", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Tambourine", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Rain Stick", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Guiro", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Cabasa", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Claves", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Agogô", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Shekere", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Talking Drum", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Gong", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Chimes", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Celesta", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Music Box", "topic": "Instruments", "difficulty": "Easy" },
{ "word": "Hurdy-Gurdy", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Glass Armonica", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Waterphone", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Ondes Martenot", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Mellotron", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Sampler", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Drum Machine", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Turntables", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Vocoder", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Talk Box", "topic": "Instruments", "difficulty": "Hard" },
{ "word": "Keytar", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "MIDI Controller", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "Launchpad", "topic": "Instruments", "difficulty": "Medium" },
{ "word": "MPC", "topic": "Instruments", "difficulty": "Hard" },

// --- PERCUSSION SPECIALTY ---
{ "word": "Tambourine", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Maracas", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Triangle", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Cymbals", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Snare Drum", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Bass Drum", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Timpani", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Glockenspiel", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Marimba", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Vibraphone", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Castanets", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Congas", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Bongos", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Cowbell", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Wood Block", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Tom-Tom", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Floor Tom", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Kick Drum", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Hi-Hat", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Ride Cymbal", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Crash Cymbal", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Splash Cymbal", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "China Cymbal", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Sleigh Bells", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Jingle Bells", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Temple Blocks", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Clap", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Stomp", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Finger Snap", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Clap Box", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Shaker", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Egg Shaker", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Caxixi", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Ratchet", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Slapstick", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Thunder Sheet", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Wind Chimes", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Mark Tree", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Cabasa", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Guiro", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Cuica", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Flexatone", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Agogo Bells", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Crotales", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Tam-Tam", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Tubular Bells", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Chime Bar", "topic": "Percussion", "difficulty": "Easy" },
{ "word": "Bell Plate", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Anvil", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Bell Tree", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Jam Block", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Timbales", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Surdo", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Repinique", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Pandeiro", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Riq", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Bendir", "topic": "Percussion", "difficulty": "Hard" },
{ "word": "Frame Drum", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Ocean Drum", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Spring Drum", "topic": "Percussion", "difficulty": "Medium" },
{ "word": "Lion's Roar", "topic": "Percussion", "difficulty": "Hard" },

// --- MUSIC THEORY & TERMS ---
{ "word": "Melody", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Rhythm", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Tempo", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Harmony", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Dynamics", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Crescendo", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Staccato", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Legato", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Fortissimo", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Pianissimo", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Syncopation", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Interval", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Arpeggio", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Chromatic", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Dissonance", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Fermata", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Adagio", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Allegro", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Andante", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Vibrato", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Metronome", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Chorus", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Ensemble", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Ostinato", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Glissando", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Decrescendo", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Diminuendo", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Accelerando", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Ritardando", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Rallentando", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Rubato", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "A Tempo", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Presto", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Largo", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Moderato", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Vivace", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Lento", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Grave", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Pizzicato", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Tremolo", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Trill", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Mordent", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Turn", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Grace Note", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Appoggiatura", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Acciaccatura", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Portamento", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Sforzando", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Forte", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Piano", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Mezzo Forte", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Mezzo Piano", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Fortepiano", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Accent", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Tenuto", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Marcato", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Sostenuto", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Articulation", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Phrasing", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Cadence", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Modulation", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Transposition", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Counterpoint", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Polyphony", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Homophony", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Monophony", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Texture", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Timbre", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Tone Color", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Pitch", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Octave", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Scale", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Major Scale", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Minor Scale", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Pentatonic", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Blues Scale", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Whole Tone Scale", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Diminished Scale", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Chord", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Triad", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Seventh Chord", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Ninth Chord", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Suspended Chord", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Augmented Chord", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Diminished Chord", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Inversion", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Root Note", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Tonic", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Dominant", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Subdominant", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Leading Tone", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Mediant", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Submediant", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Supertonic", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Consonance", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Resolution", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Suspension", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Anticipation", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Passing Tone", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Neighbor Tone", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Pedal Point", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Ostinato", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Motif", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Theme", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Variation", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Development", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Exposition", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Recapitulation", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Coda", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Intro", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Outro", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Bridge", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Verse", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Refrain", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Hook", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Riff", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Lick", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Vamp", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Turnaround", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Break", "topic": "Music Terms", "difficulty": "Easy" },
{ "word": "Fill", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Run", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Lilt", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Swing", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Groove", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Pocket", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Backbeat", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Downbeat", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Upbeat", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Offbeat", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Polyrhythm", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Cross-Rhythm", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Hemiola", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Meter", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Compound Time", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Simple Time", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Cut Time", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Common Time", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Odd Meter", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Mixed Meter", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Anacrusis", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Pickup", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Hocket", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Canon", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Fugue", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Round", "topic": "Music Terms", "difficulty": "Medium" },
{ "word": "Imitation", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Augmentation", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Diminution", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Retrograde", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Inversion", "topic": "Music Terms", "difficulty": "Hard" },
{ "word": "Sequence", "topic": "Music Terms", "difficulty": "Hard" },

// --- COMPOSERS ---
{ "word": "Bach", "topic": "Composers", "difficulty": "Easy" },
{ "word": "Mozart", "topic": "Composers", "difficulty": "Easy" },
{ "word": "Beethoven", "topic": "Composers", "difficulty": "Easy" },
{ "word": "Vivaldi", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Tchaikovsky", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Chopin", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Brahms", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Debussy", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Stravinsky", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Wagner", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Handel", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Haydn", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Schubert", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Gershwin", "topic": "Composers", "difficulty": "Hard" },
{ "word": "John Williams", "topic": "Composers", "difficulty": "Easy" },
{ "word": "Liszt", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Rachmaninoff", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Mahler", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Dvorak", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Verdi", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Puccini", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Rossini", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Bizet", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Mendelssohn", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Schumann", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Strauss", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Richard Strauss", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Johann Strauss", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Prokofiev", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Shostakovich", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Ravel", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Saint-Saens", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Berlioz", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Satie", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Grieg", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Sibelius", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Elgar", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Holst", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Vaughan Williams", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Bartok", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Kodaly", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Copland", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Bernstein", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Barber", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Sousa", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Paganini", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Monteverdi", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Palestrina", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Purcell", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Telemann", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Gluck", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Faure", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Bruckner", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Weber", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Respighi", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Rimsky-Korsakov", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Mussorgsky", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Borodin", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Scriabin", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Janacek", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Smetana", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Nielsen", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Ives", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Schoenberg", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Berg", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Webern", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Messiaen", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Britten", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Poulenc", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Hindemith", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Orff", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Ligeti", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Penderecki", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Glass", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Reich", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Adams", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Arvo Part", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Hans Zimmer", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Ennio Morricone", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Danny Elfman", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Howard Shore", "topic": "Composers", "difficulty": "Medium" },
{ "word": "James Horner", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Alan Silvestri", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Randy Newman", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Yann Tiersen", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Ludovico Einaudi", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Max Richter", "topic": "Composers", "difficulty": "Hard" },
{ "word": "Eric Whitacre", "topic": "Composers", "difficulty": "Medium" },
{ "word": "John Rutter", "topic": "Composers", "difficulty": "Medium" },
{ "word": "Karl Jenkins", "topic": "Composers", "difficulty": "Medium" },

// --- MUSIC GENRES ---
{ "word": "Classical", "topic": "Genres", "difficulty": "Easy" },
{ "word": "Jazz", "topic": "Genres", "difficulty": "Easy" },
{ "word": "Rock", "topic": "Genres", "difficulty": "Easy" },
{ "word": "Pop", "topic": "Genres", "difficulty": "Easy" },
{ "word": "Hip Hop", "topic": "Genres", "difficulty": "Easy" },
{ "word": "Country", "topic": "Genres", "difficulty": "Easy" },
{ "word": "Blues", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Reggae", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Opera", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Folk", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Bluegrass", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Baroque", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Heavy Metal", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Electronic", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Ska", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Punk", "topic": "Genres", "difficulty": "Easy" },
{ "word": "Funk", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Soul", "topic": "Genres", "difficulty": "Medium" },
{ "word": "R&B", "topic": "Genres", "difficulty": "Easy" },
{ "word": "Gospel", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Disco", "topic": "Genres", "difficulty": "Medium" },
{ "word": "House", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Techno", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Trance", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Dubstep", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Drum and Bass", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Ambient", "topic": "Genres", "difficulty": "Medium" },
{ "word": "EDM", "topic": "Genres", "difficulty": "Easy" },
{ "word": "Trap", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Grunge", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Alternative", "topic": "Genres", "difficulty": "Easy" },
{ "word": "Indie", "topic": "Genres", "difficulty": "Easy" },
{ "word": "Emo", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Screamo", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Post-Rock", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Shoegaze", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Grindcore", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Death Metal", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Black Metal", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Thrash Metal", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Progressive Rock", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Psychedelic Rock", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Glam Rock", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Surf Rock", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Garage Rock", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Rockabilly", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Swing", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Bebop", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Cool Jazz", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Hard Bop", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Free Jazz", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Fusion", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Latin Jazz", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Smooth Jazz", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Ragtime", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Dixieland", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Bossa Nova", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Samba", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Salsa", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Merengue", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Cumbia", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Tango", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Flamenco", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Mariachi", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Tejano", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Zydeco", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Cajun", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Celtic", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Klezmer", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Polka", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Waltz", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Reel", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Jig", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Fado", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Bollywood", "topic": "Genres", "difficulty": "Medium" },
{ "word": "K-Pop", "topic": "Genres", "difficulty": "Easy" },
{ "word": "J-Pop", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Afrobeat", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Highlife", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Calypso", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Dub", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Dancehall", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Grime", "topic": "Genres", "difficulty": "Medium" },
{ "word": "UK Garage", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Vaporwave", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Chillwave", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Synthwave", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Lo-Fi", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Chillhop", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Drone", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Noise", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Industrial", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Goth", "topic": "Genres", "difficulty": "Medium" },
{ "word": "New Wave", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Synth-Pop", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Power Pop", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Britpop", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Madchester", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Stoner Rock", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Math Rock", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Post-Punk", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Hardcore Punk", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Pop Punk", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Ska Punk", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Folk Punk", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Chamber Pop", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Dream Pop", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Baroque Pop", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Art Pop", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Bubblegum Pop", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Teen Pop", "topic": "Genres", "difficulty": "Easy" },
{ "word": "Adult Contemporary", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Easy Listening", "topic": "Genres", "difficulty": "Easy" },
{ "word": "Lounge", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Exotica", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Muzak", "topic": "Genres", "difficulty": "Hard" },
{ "word": "New Age", "topic": "Genres", "difficulty": "Medium" },
{ "word": "World Music", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Renaissance", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Medieval", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Romantic", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Impressionism", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Minimalism", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Serialism", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Neoclassical", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Contemporary Classical", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Experimental", "topic": "Genres", "difficulty": "Medium" },
{ "word": "Avant-Garde", "topic": "Genres", "difficulty": "Hard" },
{ "word": "Acousmatic", "topic": "Genres", "difficulty": "Hard" },

// --- NOTATION & READING ---
{ "word": "Treble Clef", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Bass Clef", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Quarter Note", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Half Note", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Whole Note", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Eighth Note", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Sixteenth Note", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Sharp", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Flat", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Natural", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Staff", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Measure", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Bar Line", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Time Signature", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Key Signature", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Rest", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Ledger Line", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Dotted Note", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Triplet", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Alto Clef", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Tenor Clef", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Grand Staff", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Beam", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Stem", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Note Head", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Flag", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Tie", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Slur", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Double Bar Line", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Repeat Sign", "topic": "Notation", "difficulty": "Medium" },
{ "word": "First Ending", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Second Ending", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Dal Segno", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Da Capo", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Coda Sign", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Segno", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Fine", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Whole Rest", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Half Rest", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Quarter Rest", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Eighth Rest", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Sixteenth Rest", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Thirty-Second Note", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Sixty-Fourth Note", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Breve", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Double Whole Note", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Grace Note", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Accidental", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Double Sharp", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Double Flat", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Ottava", "topic": "Notation", "difficulty": "Hard" },
{ "word": "8va", "topic": "Notation", "difficulty": "Hard" },
{ "word": "8vb", "topic": "Notation", "difficulty": "Hard" },
{ "word": "15ma", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Clef", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Articulation Mark", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Staccato Dot", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Accent Mark", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Tenuto Mark", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Marcato Mark", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Hairpin", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Crescendo Mark", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Diminuendo Mark", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Fermata Symbol", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Breath Mark", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Caesura", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Arpeggio Sign", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Tremolo Mark", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Trill Mark", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Turn Symbol", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Mordent Symbol", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Glissando Line", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Portamento Mark", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Pedal Mark", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Sustain Pedal", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Tuplet", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Quintuplet", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Sextuplet", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Septuplet", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Duplet", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Brace", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Bracket", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Score", "topic": "Notation", "difficulty": "Easy" },
{ "word": "Part", "topic": "Notation", "difficulty": "Easy" },
{ "word": "System", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Tablature", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Chord Symbol", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Lead Sheet", "topic": "Notation", "difficulty": "Medium" },
{ "word": "Figured Bass", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Roman Numeral", "topic": "Notation", "difficulty": "Hard" },
{ "word": "Nashville Number", "topic": "Notation", "difficulty": "Hard" },

// --- SINGING & VOICE ---
{ "word": "Soprano", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Alto", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Tenor", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Bass", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Solo", "topic": "Voice", "difficulty": "Easy" },
{ "word": "Duet", "topic": "Voice", "difficulty": "Easy" },
{ "word": "Choir", "topic": "Voice", "difficulty": "Easy" },
{ "word": "A Cappella", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Falsetto", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Vibrato", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Baritone", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Humming", "topic": "Voice", "difficulty": "Easy" },
{ "word": "Melisma", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Mezzo-Soprano", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Contralto", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Countertenor", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Coloratura", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Bel Canto", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Head Voice", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Chest Voice", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Mixed Voice", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Belt", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Whistle Register", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Vocal Fry", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Vocal Range", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Tessitura", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Passaggio", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Break", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Register", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Vocal Run", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Riff", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Growl", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Scream", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Yodel", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Scat Singing", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Vocalise", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Aria", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Recitative", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Lied", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Art Song", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Vocal Harmonies", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Backing Vocals", "topic": "Voice", "difficulty": "Easy" },
{ "word": "Lead Vocals", "topic": "Voice", "difficulty": "Easy" },
{ "word": "Harmony", "topic": "Voice", "difficulty": "Easy" },
{ "word": "Trio", "topic": "Voice", "difficulty": "Easy" },
{ "word": "Quartet", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Quintet", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Sextet", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Octet", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Ensemble Singing", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Choral Music", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Barbershop", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Madrigal", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Motet", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Cantata", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Oratorio", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Mass", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Requiem", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Canticle", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Anthem", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Hymn", "topic": "Voice", "difficulty": "Easy" },
{ "word": "Psalm", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Chant", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Gregorian Chant", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Call and Response", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Unison", "topic": "Voice", "difficulty": "Easy" },
{ "word": "Polychoral", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Antiphonal", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Round Robin", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Canon Singing", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Diction", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Articulation", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Breath Support", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Diaphragm", "topic": "Voice", "difficulty": "Medium" },
{ "word": "Vocal Warm-Up", "topic": "Voice", "difficulty": "Easy" },
{ "word": "Solfege", "topic": "Voice", "difficulty": "Hard" },
{ "word": "Do Re Mi", "topic": "Voice", "difficulty": "Easy" },

// --- PERFORMANCE & STAGE ---
{ "word": "Conductor", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Orchestra", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Concert", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Recital", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Backstage", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Encore", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Podium", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Baton", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Sheet Music", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Tuning", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Rehearsal", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Improvisation", "topic": "Performance", "difficulty": "Hard" },
{ "word": "Stage Fright", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Symphony Orchestra", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Chamber Orchestra", "topic": "Performance", "difficulty": "Hard" },
{ "word": "Philharmonic", "topic": "Performance", "difficulty": "Hard" },
{ "word": "String Quartet", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Jazz Band", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Big Band", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Marching Band", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Concert Band", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Wind Ensemble", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Brass Band", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Rock Band", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Garage Band", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Cover Band", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Tribute Band", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Session Musician", "topic": "Performance", "difficulty": "Hard" },
{ "word": "Soloist", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Accompanist", "topic": "Performance", "difficulty": "Hard" },
{ "word": "Lead Guitarist", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Rhythm Guitarist", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Bassist", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Drummer", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Keyboardist", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Percussionist", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Vocalist", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Frontman", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Bandleader", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Concertmaster", "topic": "Performance", "difficulty": "Hard" },
{ "word": "First Chair", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Section Leader", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Principal Player", "topic": "Performance", "difficulty": "Hard" },
{ "word": "Understudy", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Stand-In", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Substitute", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Guest Artist", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Featured Artist", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Opening Act", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Headliner", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Sound Check", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Tech Rehearsal", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Dress Rehearsal", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Run-Through", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Stage Manager", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Sound Engineer", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Lighting Designer", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Production Manager", "topic": "Performance", "difficulty": "Hard" },
{ "word": "Roadie", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Tour Manager", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Concert Hall", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Auditorium", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Theater", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Opera House", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Amphitheater", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Arena", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Stadium", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Club", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Venue", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Music Hall", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Bandstand", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Gazebo", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Green Room", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Orchestra Pit", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Stage", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Stage Left", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Stage Right", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Upstage", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Downstage", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Center Stage", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Wings", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Curtain Call", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Bow", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Ovation", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Standing Ovation", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Applause", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Bravo", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Audience", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Crowd", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Fan", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Groupie", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Mosh Pit", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Festival", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Music Festival", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Tour", "topic": "Performance", "difficulty": "Easy" },
{ "word": "World Tour", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Residency", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Gig", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Show", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Set", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Set List", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Intermission", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Interval", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Halftime", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Jam Session", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Open Mic", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Battle of the Bands", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Showcase", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Masterclass", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Workshop", "topic": "Performance", "difficulty": "Easy" },
{ "word": "Clinic", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Audition", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Callback", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Sight Reading", "topic": "Performance", "difficulty": "Hard" },
{ "word": "Transposition", "topic": "Performance", "difficulty": "Hard" },
{ "word": "Collaboration", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Duet Partner", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Chamber Music", "topic": "Performance", "difficulty": "Hard" },
{ "word": "Musicianship", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Stage Presence", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Showmanship", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Performance Anxiety", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Adrenaline", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Memory Slip", "topic": "Performance", "difficulty": "Hard" },
{ "word": "Train Wreck", "topic": "Performance", "difficulty": "Hard" },
{ "word": "Flawless", "topic": "Performance", "difficulty": "Medium" },
{ "word": "Virtuoso", "topic": "Performance", "difficulty": "Hard" },
{ "word": "Prodigy", "topic": "Performance", "difficulty": "Medium" },

// --- FUN / MISC ---
{ "word": "Grammy", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Headphones", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Speaker", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Microphone", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Amplifier", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Playlist", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Soundtrack", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Metronome", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Vinyl Record", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Jukebox", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Album", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Single", "topic": "Misc", "difficulty": "Easy" },
{ "word": "EP", "topic": "Misc", "difficulty": "Medium" },
{ "word": "LP", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Track", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Song", "topic": "Misc", "difficulty": "Easy" },
{ "word": "B-Side", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Mixtape", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Demo", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Bootleg", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Live Album", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Studio Album", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Compilation", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Greatest Hits", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Remix", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Cover Song", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Original", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Arrangement", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Transcription", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Score", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Recording", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Recording Studio", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Mixing", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Mastering", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Producer", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Audio Engineer", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Mixing Board", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Console", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Equalizer", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Compressor", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Reverb", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Delay", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Echo", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Chorus Effect", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Flanger", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Phaser", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Distortion", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Overdrive", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Fuzz", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Wah-Wah", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Pedal", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Effects Pedal", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Pedalboard", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Looper", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Volume Pedal", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Tuner", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Pitch Pipe", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Tuning Fork", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Capo", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Pick", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Plectrum", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Strap", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Guitar Cable", "topic": "Misc", "difficulty": "Easy" },
{ "word": "XLR Cable", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Jack", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Aux Cable", "topic": "Misc", "difficulty": "Easy" },
{ "word": "MIDI", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Audio Interface", "topic": "Misc", "difficulty": "Medium" },
{ "word": "DAW", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Pro Tools", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Logic Pro", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Ableton", "topic": "Misc", "difficulty": "Medium" },
{ "word": "GarageBand", "topic": "Misc", "difficulty": "Easy" },
{ "word": "FL Studio", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Cubase", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Reaper", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Plugin", "topic": "Misc", "difficulty": "Medium" },
{ "word": "VST", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Sample", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Loop", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Beat", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Groove", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Drop", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Build-Up", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Breakdown", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Drop the Beat", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Four on the Floor", "topic": "Misc", "difficulty": "Hard" },
{ "word": "BPM", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Beats Per Minute", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Time Code", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Click Track", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Guide Track", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Scratch Track", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Overdub", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Punch-In", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Punch-Out", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Fade In", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Fade Out", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Crossfade", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Pan", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Stereo", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Mono", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Surround Sound", "topic": "Misc", "difficulty": "Medium" },
{ "word": "5.1", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Hi-Fi", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Lo-Fi", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Audiophile", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Earbuds", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Studio Monitor", "topic": "Misc", "difficulty": "Medium" },
{ "word": "PA System", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Sound System", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Subwoofer", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Tweeter", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Woofer", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Bluetooth", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Wireless", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Streaming", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Spotify", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Apple Music", "topic": "Misc", "difficulty": "Easy" },
{ "word": "YouTube Music", "topic": "Misc", "difficulty": "Easy" },
{ "word": "SoundCloud", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Bandcamp", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Tidal", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Pandora", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Radio", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Podcast", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Music Video", "topic": "Misc", "difficulty": "Easy" },
{ "word": "MTV", "topic": "Misc", "difficulty": "Medium" },
{ "word": "VH1", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Billboard", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Chart", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Top 40", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Hit Song", "topic": "Misc", "difficulty": "Easy" },
{ "word": "One-Hit Wonder", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Platinum", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Gold Record", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Diamond", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Hall of Fame", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Legend", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Icon", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Superstar", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Rockstar", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Pop Star", "topic": "Misc", "difficulty": "Easy" },
{ "word": "DJ", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Disc Jockey", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Turntablist", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Beatmaker", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Songwriter", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Lyricist", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Composer", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Arranger", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Orchestrator", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Music Theory", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Ear Training", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Perfect Pitch", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Relative Pitch", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Tone Deaf", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Music Lesson", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Practice", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Scales", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Arpeggios", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Technique", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Fingering", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Embouchure", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Bow Hold", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Posture", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Music Stand", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Instrument Case", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Gig Bag", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Hard Case", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Reed", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Mouthpiece", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Valve", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Slide", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Fret", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Fretboard", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Neck", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Headstock", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Bridge", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Saddle", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Nut", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Tuning Peg", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Machine Head", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Pickup", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Humbucker", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Single Coil", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Tremolo", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Whammy Bar", "topic": "Misc", "difficulty": "Medium" },
{ "word": "String", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Guitar String", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Violin String", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Bow", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Rosin", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Mute", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Damper", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Soundboard", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Sound Hole", "topic": "Misc", "difficulty": "Medium" },
{ "word": "F-Hole", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Resonator", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Bell", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Bore", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Key", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Pad", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Cork", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Ligature", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Drumstick", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Brush", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Mallet", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Beater", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Drum Head", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Drum Kit", "topic": "Misc", "difficulty": "Easy" },
{ "word": "Cymbal Stand", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Drum Throne", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Practice Pad", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Drum Rudiment", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Paradiddle", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Flam", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Roll", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Rimshot", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Ghost Note", "topic": "Misc", "difficulty": "Hard" },
{ "word": "Accent", "topic": "Misc", "difficulty": "Medium" },
{ "word": "Paradiddle-diddle", "topic": "Misc", "difficulty": "Hard" }
];
